package convert

const (
	bicepHeader = `// Generated by score-aca
// Azure Container Apps Bicep manifest
`

	// TODO: Pull Environment version from Azure
	bicepContainerAppEnvironment = `// Container App Environment
resource containerAppEnvironment 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: environmentName
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'azure-monitor'
    }
  }
}
`

	bicepOutputs = `
// Outputs
output containerAppFQDN string = containerApp.properties.configuration.ingress.fqdn
`
)
